package USForestRegistry;

public class StringConstants
{
	public static final String FOREST_NO = "forest_no";
	public static final String NAME = "name";
	public static final String AREA = "area";
	public static final String ACID_LEVEL = "acid_level";
	public static final String MBR_XMIN = "mbr_xmin";
	public static final String MBR_XMAX = "mbr_xmax";
	public static final String MBR_YMIN = "mbr_ymin";
	public static final String MBR_YMAX = "mbr_ymax";
	public static final String ABBREVIATION = "abbreviation";
	public static final String STATE = "state";
	public static final String SSN = "ssn";
	public static final String RANK = "rank";
	public static final String EMPLOYING_STATE = "employing_state";
	public static final String SENSOR_ID = "sensor_id";
	public static final String X = "x";
	public static final String Y = "y";
	public static final String LAST_CHARGED = "last_charged";
	public static final String MAINTAINER = "maintainer";
	public static final String LAST_READ = "last_read";
	public static final String ENERGY = "energy";
	public static final String WORKER_A_NAME = "Worker A's name";
	public static final String WORKER_B_NAME = "Worker B's name";
	public static final String REPORT_TIME = "report_time";
	public static final String TEMPERATURE = "temperature";
	public static final String PERCENTAGE = "percentage";
	public static final String HOSTNAME = "hostname";
	public static final String PORT = "port";
	public static final String DATABASE_NAME = "database name";
	public static final String USERNAME = "username";
	public static final String PASSWORD = "password";
	public static final String COVERAGE = "coverage";
	public static final String FOREST = "forest";
	public static final String INTERSECTION = "intersection";
	public static final String REPORT = "report";
	public static final String ROAD = "road";
	public static final String SENSOR = "sensor";
	public static final String WORKER = "worker";
	public static final String INSERT = "Insert";
	public static final String UPDATE = "Update";
	public static final String QUERY = "Query";
	public static final String ADD_FOREST = "Add Forest";
	public static final String ADD_WORKER = "Add Worker";
	public static final String ADD_SENSOR = "Add Sensor";
	public static final String SWITCH_WORKERS_DUTIES = "Switch Workers' Duties";
	public static final String UPDATE_SENSOR_STATUS = "Update Sensor Status";
	public static final String UPDATE_FOREST_COVERED_AREA = "Update Forest Covered Area";
	public static final String FIND_TOP_K_BUSY_WORKERS = "Find Top K Busy Workers";
	public static final String DISPLAY_SENSORS_RANKING = "Display Sensors Ranking";
	public static final String STATE_ABBREVIATION = STATE + "_" + ABBREVIATION;
	public static final String DOTS = "...";
}
