package USForestRegistry;

/**
 * String constants that are referenced in multiple places in the application.
 */
public class StringConstants
{
	public static final String 
	FOREST_NO = "forest_no",
	NAME = "name",
	FOREST_NAME = "forest_name",
	AREA = "area",
	ACID_LEVEL = "acid_level",
	MBR_XMIN = "mbr_xmin",
	MBR_XMAX = "mbr_xmax",
	MBR_YMIN = "mbr_ymin",
	MBR_YMAX = "mbr_ymax",
	ABBREVIATION = "abbreviation",
	STATE = "state",
	SSN = "ssn",
	RANK = "rank",
	EMPLOYING_STATE = "employing_state",
	SENSOR_ID = "sensor_id",
	X = "x",
	Y = "y",
	K = "K",
	LAST_CHARGED = "last_charged",
	MAINTAINER = "maintainer",
	LAST_READ = "last_read",
	ENERGY = "energy",
	WORKER_A_NAME = "Worker A's name",
	WORKER_B_NAME = "Worker B's name",
	TEMPERATURE = "temperature",
	HOSTNAME = "hostname",
	PORT = "port",
	DATABASE_NAME = "database name",
	USERNAME = "username",
	PASSWORD = "password",
	COVERAGE = "coverage",
	FOREST = "forest",
	INTERSECTION = "intersection",
	REPORT = "report",
	ROAD = "road",
	SENSOR = "sensor",
	WORKER = "worker",
	INSERT = "Insert",
	UPDATE = "Update",
	QUERY = "Query",
	ADD_FOREST = "Add Forest",
	ADD_WORKER = "Add Worker",
	ADD_SENSOR = "Add Sensor",
	SWITCH_WORKERS_DUTIES = "Switch Workers' Duties",
	UPDATE_SENSOR_STATUS = "Update Sensor Status",
	UPDATE_FOREST_COVERED_AREA = "Update Forest Covered Area",
	FIND_TOP_K_BUSY_WORKERS = "Find Top K Busy Workers",
	DISPLAY_SENSORS_RANKING = "Display Sensors Ranking",
	STATE_ABBREVIATION = STATE + "_" + ABBREVIATION,
	EMPLOYING_STATE_ABBREVIATION = EMPLOYING_STATE + "_" + ABBREVIATION,
	DOTS = "...";
}
